/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import javax.swing.JOptionPane;
import controllers.ARadministrador;
import controllers.AlumnosController;
import controllers.ControllerLogin;
import controllers.DocenteController;

/**
 *
 * @author franz
 */
public class Login extends javax.swing.JDialog {
    
    private ControllerLogin ver = new ControllerLogin();
    private ARadministrador adm = new ARadministrador();
    private DocenteController doc = new DocenteController();
    private AlumnosController est = new AlumnosController();
            

    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ver.CrearAdministrador();
        limpiar();
    }
    
    public void inicioSesion() {
        if (txtcorreo.getText().trim().isEmpty() || txtcontraseña.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Faltan Datos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String[] data = ver.verificarcontraseña(txtcorreo.getText(), String.valueOf(txtcontraseña.getPassword()));
            if (data != null) {
                String[] admin = ver.verificarCedula(data[0], adm.listar());
                if (admin != null) {
                    JOptionPane.showMessageDialog(null, "Bienvenido administrador: "+admin[3]+","+admin[2], "Mensaje de exito", JOptionPane.INFORMATION_MESSAGE);
                    new PaguinaAdministrador().setVisible(true);
                    dispose();
                } 
                String[] docen = ver.verificarCedula(data[0], doc.listar());
                if (docen!=null) {
                    JOptionPane.showMessageDialog(null, "Bienvenido docente: "+docen[3]+","+docen[2], "Mensaje de exito", JOptionPane.INFORMATION_MESSAGE);
                    
                    dispose();
                } 
                String[] estud = ver.verificarCedula(data[0], est.listar());
                if (estud!=null) {
                    JOptionPane.showMessageDialog(null, "Bienvenido estudeiante: "+estud[3]+","+estud[2], "Mensaje de exito", JOptionPane.INFORMATION_MESSAGE);
                    new Sistemalumnos(new javax.swing.JFrame(), true).setVisible(true);
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Correo o contraseña incorectos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    public void limpiar(){
        txtcorreo.setText("");
        txtcontraseña.setText("");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtcorreo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtcontraseña = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicio de sesion ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 420, 24);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        jPanel3.setLayout(null);

        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });
        jPanel3.add(txtcorreo);
        txtcorreo.setBounds(5, 17, 240, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(85, 60, 250, 60);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        jPanel2.setLayout(null);
        jPanel2.add(txtcontraseña);
        txtcontraseña.setBounds(7, 18, 240, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(85, 120, 250, 60);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("Iniciar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 200, 120, 26);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 330);

        setSize(new java.awt.Dimension(430, 367));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        inicioSesion();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtcorreo;
    // End of variables declaration//GEN-END:variables
}
