/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import Tablas.ModeloTabla;
import controllers.DocenteController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Usuario
 */
public class ModuloDeDocentes extends javax.swing.JDialog {

    ModeloTabla mlt = new ModeloTabla();
    DocenteController controlador = new DocenteController();

    /**
     * Creates new form ModuloDeDocentes
     */
    public ModuloDeDocentes(java.awt.Frame parent, boolean modal, String nombreDocente) throws IOException {
        super(parent, modal);
        initComponents();

        jLabel6.setText(nombreDocente);
        cargarTabla();
        
        JButton[] botonesMaterias = {btnMateria1, btnMateria2, btnMateria3, btnMateria4};

        for (JButton boton : botonesMaterias) {
            boton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    String materiaSeleccionada = boton.getText();
                    jLabel5.setText(materiaSeleccionada);
                    try {
                        cargarTablaPorMateria(materiaSeleccionada);
                        cargarEstudiantesPorMateria(materiaSeleccionada);
                    } catch (IOException ex) {
                        Logger.getLogger(ModuloDeDocentes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
        }
    }

    private void cargarTabla() throws IOException {
        mlt.setData(controlador.listar());
        jTable2.setModel(mlt);
        jTable2.updateUI();
    }
    
    
    private void cargarTablaPorMateria(String materia) throws IOException {
    String[][] data = controlador.listarPorMateria(materia); 
    mlt.setData(data);
    jTable2.setModel(mlt);
    jTable2.updateUI();
}
    
    private void cargarEstudiantesPorMateria(String materia) throws IOException {
    String[][] data = controlador.listarPorMateria(materia); 
    String[] estudiantes = new String[data.length];

    for (int i = 0; i < data.length; i++) {
        estudiantes[i] = data[i][1]; 
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnMateria1 = new javax.swing.JButton();
        btnMateria2 = new javax.swing.JButton();
        btnMateria3 = new javax.swing.JButton();
        btnMateria4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(252, 241, 210));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(239, 195, 98));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel1.setText("Area de Docentes");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 0, 210, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Docente: ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 40, 60, 16);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 50, 70, 0);

        jLabel6.setText("Ing. Jeam Romero");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(80, 40, 150, 16);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 640, 70);

        jPanel3.setBackground(new java.awt.Color(239, 195, 98));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 40, 620, 190);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel5.setText("Materia 1");
        jLabel5.setAutoscrolls(true);
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 10, 110, 21);

        jButton1.setText("Asignar Nota");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(495, 10, 130, 23);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 190, 640, 260);

        jPanel5.setBackground(new java.awt.Color(239, 195, 98));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setForeground(new java.awt.Color(255, 153, 153));
        jPanel5.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel7.setText("Materias");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(20, 10, 90, 21);

        btnMateria1.setText("Matemáticas");
        btnMateria1.setBorder(new javax.swing.border.MatteBorder(null));
        btnMateria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateria1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnMateria1);
        btnMateria1.setBounds(20, 40, 130, 30);

        btnMateria2.setText("Física");
        btnMateria2.setBorder(new javax.swing.border.MatteBorder(null));
        btnMateria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateria2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnMateria2);
        btnMateria2.setBounds(170, 40, 130, 30);

        btnMateria3.setText("Ingles");
        btnMateria3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel5.add(btnMateria3);
        btnMateria3.setBounds(330, 40, 130, 30);

        btnMateria4.setText("Lengua");
        btnMateria4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel5.add(btnMateria4);
        btnMateria4.setBounds(480, 40, 130, 30);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(20, 100, 640, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 510);

        setSize(new java.awt.Dimension(704, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnMateria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateria1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnMateria1ActionPerformed

    private void btnMateria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateria2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMateria2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloDeDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloDeDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloDeDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloDeDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModuloDeDocentes dialog = null;
                try {
                    dialog = new ModuloDeDocentes(new javax.swing.JFrame(), true, "Ing. Jeam Romero");
                } catch (IOException ex) {
                    Logger.getLogger(ModuloDeDocentes.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMateria1;
    private javax.swing.JButton btnMateria2;
    private javax.swing.JButton btnMateria3;
    private javax.swing.JButton btnMateria4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
