/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import controllers.AlumnosController;
import modeloTabla.ModeloTablaNotas;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario iTC
 */
public class Sistemalumnos extends javax.swing.JDialog {
    public Sistemalumnos(java.awt.Frame parent, boolean modal) {
        super (parent, modal);
        initComponents();
        cargarDatos();
    }

    private double parseNota(String valor) {
    if (valor == null || valor.trim().isEmpty()) {
        return 0.0;
    }
    try {
        return Double.parseDouble(valor);
    } catch (NumberFormatException e) {
        return 0.0;
    }
}
    private void cargarDatos(){
        String correoSimulado = "juanperez@unl.edu.ec";
        
        AlumnosController ac = new AlumnosController();
        String [][] datos = ac.buscarPorcorreo(correoSimulado);
        
        if (datos.length == 0){
            JOptionPane.showMessageDialog(this, "No se encontraron datos para el correo: " + correoSimulado);
            return;
        }
       
        String cedula = datos [0][0];
        String [][] datosNotas = ac.buscarNotasPorCedula(cedula);
        if(datosNotas.length == 0){
            JOptionPane.showMessageDialog(this, "No se encontraron notas para el alumno con cédula: " + cedula);
            return;
        }
        estudiante.setText(datos[0][1] + " " + datos [0][2]);
        id.setText(datos[0][0]);
        correo.setText(datos[0][4]);
        jLabel6.setText(datos[0][5]);
        
        int filas = datosNotas.length;
        String [][] notasParaTabla = new String [filas][4];
        for (int i = 0; i < filas; i++){
            notasParaTabla[i][0] = datosNotas[i][0];
            notasParaTabla[i][1] = datosNotas[i][1];
            notasParaTabla[i][2] = datosNotas[i][2];
            notasParaTabla[i][3] = datosNotas[i][3];
            
        }
        jTable2.setModel(new ModeloTablaNotas(notasParaTabla));
        
        double suma = 0;
        for (String [] fila : datosNotas){
            double n1 = parseNota(fila[1]);
            double n2 = parseNota(fila[2]);
            double n3 = parseNota(fila[3]);
            suma += (n1 + n2 + n3) / 3;
            
        }
        double promedioFinal = suma / notasParaTabla.length;
        total2.setText(String.format("%.2f", promedioFinal));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        estudiante = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        total2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alumnos");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA DE CALIFICACIONES ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 10, 450, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Estudiante:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 50, 110, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("CÉDULA:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 90, 80, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Correo Electrónico:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(220, 90, 170, 20);

        estudiante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(estudiante);
        estudiante.setBounds(120, 50, 210, 30);

        id.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(id);
        id.setBounds(100, 90, 100, 20);

        correo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(correo);
        correo.setBounds(360, 90, 190, 20);

        jLabel5.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        jLabel5.setText("Grado:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 50, 80, 24);

        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 50, 110, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 20, 570, 130);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MATERIA", "UNIDAD 1", "UNIDAD 2", "UNIDAD 3", "PROMEDIO"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 170, 570, 110);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("Resumen:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 10, 110, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel9.setText("Materias: ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 50, 120, 32);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("5");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(140, 50, 40, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel11.setText("Promedio Total:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(200, 50, 200, 32);

        total2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        total2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.add(total2);
        total2.setBounds(420, 50, 140, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 290, 570, 100);

        jButton1.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        jButton1.setText("Detalles");
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 400, 120, 31);

        setSize(new java.awt.Dimension(628, 493));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
        public static void main(String[] args) {
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sistemalumnos dialog = new Sistemalumnos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correo;
    private javax.swing.JLabel estudiante;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel total2;
    // End of variables declaration//GEN-END:variables
}
